[package]
name = "raphle-experimental"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
hashbrown = "0.14.3"
roaring = "0.10.3"
rusqlite = "0.31.0"
tracing = "0.1.40"
